### ISSUE TITLE
unpaywall.js console.log

### ISSUE THREAD

**Issue by mbhall88** [Impactstory/unpaywall#11]
Noticed that when opening the developer console in chrome there are two lines that have been console.logged from unpaywall.js (line 12) in the extensions folder. Is this necessary? 

```
unpaywall: unpaywall is running undefined
unpaywall: got settings [Object]
```

**Comment by richard-orr** [comment]
This was partially addressed in b1b39335, although Nerd Mode and log level settings should be orthogonal.

Moved to https://support.unpaywall.org/public/tickets/cd5d16c282bbedbf7ca62fc0f8ac538bf48d7a77e20edb7eb85d870534511246
