### ISSUE TITLE
Redirect from one paywall to another paywall (INFORMS to JSTOR)

### ISSUE THREAD

**Issue by moqri** [Impactstory/unpaywall#13]
Example: http://pubsonline.informs.org/doi/abs/10.1287/isre.2.3.173
Redirects to: http://www.jstor.org/stable/23010882

**Comment by eocarragain** [comment]
Google Scholar seems to be the culprit here. Perhaps certain domains (like jstor.org) should be filtered if returned by GS?

GS (jstor link): https://api.oadoi.org/gs/cache/10.1287/isre.2.3.173

OADOI (no fulltext): https://api.oadoi.org/10.1287/isre.2.3.173

**Comment by ioverka** [comment]
Cannot reproduce this issue any longer.

**Comment by richard-orr** [comment]
Closing as the involved functionality no longer exists. https://api.oadoi.org/gs/cache/10.1287/isre.2.3.173?email=richard@unpaywall.org and https://api.oadoi.org/10.1287/isre.2.3.173?email=richard@unpaywall.org are handled identically and do not involve Google Scholar.
