### ISSUE TITLE
Add-on changes the way Firefox parses XML

### ISSUE THREAD

**Issue by truboxl** [Impactstory/unpaywall#15]
Not exactly a problem to the general public, but I notice Unpaywall does interfere the way Firefox parse XML, maybe similar to https://support.mozilla.org/en-US/questions/1074505

Try enable/disable Unpaywall when you open the link below...
http://www.xmlfiles.com/examples/note.xml

**Comment by iGormilhit** [comment]
I have been noticing the same problem when wanting to display the xml export of an Institutional repository.

http://doc.rero.ch/record/289137/export/xm

**Comment by ejoliet** [comment]
Almost a year since issue raised, the extension in Firefox still disables the XML pretty formatting. Any chance to see a fix soon? Thanks!

**Comment by mlinksva** [comment]
Possibly similar issue: https://github.com/keepassxreboot/keepassxc-browser/pull/128

It seems their fix is to remove jquery. Presumably there's an easier fix -- don't run if content type is `text/xml`?

**Comment by niederlec** [comment]
@mlinksva I can confirm what you say.
In the past, we had the same problem in our [ISTEX extension](https://github.com/istex/istex-browser-extension), which do almost the same thing that Unpaywall (insert a button if a document is available in the french archive platform ISTEX)
We have chosen to not process page with "text/xml" or "application/xml" mimetypes. (see [this bugfix](https://github.com/istex/istex-browser-extension/commit/bf7dda036afe16b4ceb044f278d06c77455daa12))

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/326392131b0bdbe125f2f563ae4082d35142a18248377f3a616da3a2dee5703e
