### ISSUE TITLE
unpaywall.org isn't HTTPS

### ISSUE THREAD

**Issue by ssg** [Impactstory/unpaywall#18]
Plain HTTP allows a man-in-the-middle attacker to serve a phishing site which might direct user to install a malicious extension or download arbitrary files instead of the actual extension. That is especially problematic for academic personnel because they commonly use a network shared by hundreds of people.

**Comment by jasonpriem** [comment]
Thanks. This is scheduled to be done. FWIW the actual extension (where I think security is a bigger concern) does exclusively use HTTPS, as does the underlying oaDOI API and website.

But agreed we need to upgrade the unpaywall.org site as well. Will leave this issue open until it's done.

**Comment by mlinksva** [comment]
I don't know when it was done, but this appears to be fixed now, though there appear to be [some links](https://github.com/search?q=org%3AImpactstory+%22http%3A%2F%2Funpaywall.org%22&type=Code) that could be upgraded. 😄

**Comment by ssg** [comment]
It is working on HTTPS but defaults to HTTP, so still susceptible to MITM. Adding HSTS headers would fix this.

**Comment by hpiwowar** [comment]
Good to know!  Thanks!
Heather

--
Heather Piwowar, cofounder
Impactstory <http://impactstory.org/>: We make tools to power the Open
Science revolution
follow at @researchremix <https://twitter.com/researchremix>, @impactstory
<http://twitter.com/impactstory>, and @unpaywall
<https://twitter.com/unpaywall>

**Comment by mariusa** [comment]
I still get http://unpaywall.org/ by default

Can I help on getting this done?
FYI Netlify offers free static website hosting with SSL, and proxy API requests to a backend too:
https://www.netlify.com/

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/7583cdec5455e15a9d3de63bdd23a5f04096f56de58937c5bd3523c3589a639a
