### ISSUE TITLE
Is unpaywall working in Scopus?

### ISSUE THREAD

**Issue by ioverka** [Impactstory/unpaywall#20]
The button is there, but the information about free availability isn't displayed.

Example Record:
```
Artificial Intelligence, Volume 241, 1 December 2016, Pages 1-44
Integrating social power into the decision-making of cognitive agents(Article)
by: Pereira, G.Email Author, Prada, R.Email Author, Santos, P.A.Email Author View Correspondence (jump link) 
DOI: 10.1016/j.artint.2016.08.003
```

![scopus](https://user-images.githubusercontent.com/8920469/30379755-d9c6b130-9897-11e7-9116-f56f024e8f32.png)

According to oaDOI, "is_free_to_read" is true: http://api.oadoi.org/10.1016/j.artint.2016.08.003

**Comment by hpiwowar** [comment]
Good find.  Is a bug.  Looking into it.  Thanks!
Heather

--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by researchremix** [comment]
I think we've fixed this, though I don't have access to Scopus to check.
Could you check?  Thanks!  :)

Heather

--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by ioverka** [comment]
Yeah, I just found a couple of green & gold unpaywall locks in Scopus records! And linking works fine as well ;)

**Comment by ioverka** [comment]
Thanks a lot for the fix!

**Comment by hpiwowar** [comment]
Great!  I'm glad :)
