### ISSUE TITLE
American Mathematical Society free articles

### ISSUE THREAD

**Issue by pkra** [Impactstory/unpaywall#22]
The American Mathematical Society has a moving wall of 5 years after which all journal articles become freely available.  See, e.g., https://www.ams.org/journals/jams/all_issues.html.

It would be great if those articles could be picked up by unpaywall.

(Authors are also encouraged to deposit their final manuscript on arXiv.org but IIUC oadoi doesn't try to find articles in the arXiv heuristically.)

**Comment by hpiwowar** [comment]
Hi Peter.  Totally agree!  I think unpaywall should pick those up now... if you have a specific page where it isn't working, let us know and we'll fix it :)
Thanks! 
Heather
