### ISSUE TITLE
Firefox plugin broken for PubMedCentral records? Grey vs. Green

### ISSUE THREAD

**Issue by ioverka** [Impactstory/unpaywall#23]
Tested with:
- Firefox plugin, version Unpaywall 1.5 = display in PMC broken, grey icon displayed 
- Chrome plugin, version Unpaywall 3.2 = display in PMC works fine, bronze icon displayed

PMC URL: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5484110/

In PubMedCentral:
![image](https://user-images.githubusercontent.com/8920469/33112268-a6eaff54-cf52-11e7-88f1-cc13197306c7.png)

On publisher website:
![image](https://user-images.githubusercontent.com/8920469/33112301-cf9b43f0-cf52-11e7-86b3-da548d8e65ac.png)

**Comment by hpiwowar** [comment]
Thanks!  We'll be releasing a new Firefox version soon.
Best,
Heather

--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by hpiwowar** [comment]
Fixed!
