### ISSUE TITLE
No unpaywall icon loaded for T&F abstract page

### ISSUE THREAD

**Issue by ioverka** [Impactstory/unpaywall#24]
tested with: Firefox plugin, version Unpaywall 1.5

record URL: http://www.tandfonline.com/doi/full/10.1080/10508422.2016.1193439

![image](https://user-images.githubusercontent.com/8920469/33113017-7597c410-cf56-11e7-95ec-57ea15061bfd.png)

**Comment by hpiwowar** [comment]
Thanks for letting us know.  These are all showing up for me, so we need a
bit more help debugging.  What browser/OS are you testing with?  Thanks!


--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by ioverka** [comment]
It's Firefox 56/Win 7

Chrome seems to be fine (once again).

The icon is loaded for some T&F pages, e.g.
http://www.tandfonline.com/doi/abs/10.1080/10632921.1995.9941791
http://www.tandfonline.com/doi/abs/10.1080/1600910X.2009.9672741
http://www.tandfonline.com/doi/abs/10.1080/00664677.1991.9967418

... but not for all. Further examples with missing icons are:
http://www.tandfonline.com/doi/full/10.1080/21692327.2013.771913
http://www.tandfonline.com/doi/abs/10.1080/00062278.1976.10597121
http://www.tandfonline.com/doi/full/10.1080/03060497.2016.1249123

BTW: The ACS and BMJ examples had been wrong... in these cases the display of the icon was only delayed (-> that's the reason for the edit of the description).

**Comment by hpiwowar** [comment]
fixed!
