### ISSUE TITLE
Enhancement: Offer the option to paste a DOI

### ISSUE THREAD

**Issue by ioverka** [Impactstory/unpaywall#25]
Some user feedback: 

It would be helpful if the plugin would offer the possibility to paste a DOI to be checked explicitly, e.g. because
a. the icon is missing completely (see #24)
b. the display of the icon is delayed (noticed for ACS, BMJ)
c. the information provided is incorrect (see #23) and should be verified

**Comment by d0mf1g** [comment]
Good idea. Would be nice to input the DOI by clicking on the toolbar icon.

**Comment by jasonpriem** [comment]
Thanks for the feedback, y'all. Will continue to watch this issue to see if it accumulates more +1s

**Comment by ioverka** [comment]
... switching into promote mode ;)

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/5ceb0462bb34c3acbfb6a1c45c5382d9680ef1b467ea9854191ff6865f99bc3f
