### ISSUE TITLE
Most repository pages show a 'Bronze' tab with nerd mode enabled.

### ISSUE THREAD

**Issue by eocarragain** [Impactstory/unpaywall#27]
Hi,
I've had a read through unpaywall.js and it seems to me as if most Green repositories will get a Bronze tab on the plugin. To summarise my understanding of how it is working. Having identified a DOI from meta tags, etc.:

- unpaywall queries oadoi by the doi. If the preferred OA source in the API has 'repository' as the host_type, this is considered 'Green'
- unpayall also tries to find a pdf on the current page by looking the the citation_pdf_url meta tag and similar locations. The local pdf source is always set to 'Bronze'
- In deciding on what to display, the getBestOaUrl() and decideTabColor() functions always give preference the local pdf as the source. 
- In practice this means that even if I'm on a repository page and oadoi has identified the same page as the best OA source and has correctly identified the host_type as repository (so OADOI considers it green), the tab still displays as bronze because the local pdf path gets preference and doesn't know that it is a repository page

This isn't serious as I'd imagine very few people have the 'nerd mode' enabled, so they'll see green in any case. Just logging here for reference

Example for reference: https://cora.ucc.ie/handle/10468/3163

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/7124b352ca94845003a0d39ed7ca4ecd5170be2b655565d74803554db7b470f9
