### ISSUE TITLE
unpaywall as firefox add-on fails to direct to the correct pubmed central page

### ISSUE THREAD

**Issue by laurentperrinet** [Impactstory/unpaywall#29]
Trying to access this paper:

https://www.mitpressjournals.org/doi/full/10.1162/NECO_a_00332

the extension gives a correct green icon showing there's a legit OA alternative, but fails to link to the correct address which is

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3472550

and not 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3472550/pdf/

Thanks,
Laurent

**Comment by hpiwowar** [comment]
Thanks for the bug report.  Fixed!
