### ISSUE TITLE
Differentiate between hybrid open access & open access journal

### ISSUE THREAD

**Issue by peterdesmet** [Impactstory/unpaywall#3]
Fantastic work creating unpaywall! 👏  Also neat that one can differentiate between green and golden open access.

As you know, golden OA can take two forms: open access journals (which is a business model I'd like to support) and hybrid OA, in which subscription journals use both subscriptions and (high) APC as two sources of revenue. I believe the oadoi.org API makes the [difference between these two](https://api.oadoi.org/10.1016/j.scitotenv.2016.02.024) (`oa_color": "gold` AND `is_subscription_journal": true`)?

Does that mean it would be possible to make that difference in the unpaywall tab? I'd fully understand if you don't want to indicate that difference, because for the reader of an article it doesn't really matter. But for OA nerds like me, it does. 😄

**Comment by richard-orr** [comment]
Greetings from 2019! Unpaywall now has an OA Nerd Mode setting, which distinguishes between bronze/hybrid and gold OA. e.g. Gold: [10.1186/s13638-016-0717-y](https://doi.org/10.1186/s13638-016-0717-y), Hybrid: [10.1006/jcta.2002.3267](https://doi.org/10.1006/jcta.2002.3267).

The relevant fields in [V2 of the API](https://api.oadoi.org/v2/10.1016/j.scitotenv.2016.02.024?email=richard@impactstory.org) are now journal_is_oa and oa_status.
