### ISSUE TITLE
False negative for manuscript hosted on institutional repository "hal"

### ISSUE THREAD

**Issue by cmaumet** [Impactstory/unpaywall#36]
Dear unpaywall team,

Thank you for developing such a nice tool! 

I have found a couple of false negatives:
 - http://dx.doi.org/10.1016/j.neuroimage.2016.03.054 >> http://www.hal.inserm.fr/inserm-01291748/file/Maumet_NeuroImage_A_Contrario.pdf
 - https://doi.org/10.1016/j.neuroimage.2013.04.079 >> http://www.hal.inserm.fr/inserm-00816852/file/Maumet_NeuroImage_2013.pdf

I have checked and the source repository "HAL" (both hal Inria & hal Inserm) seems to be available in your [data sources](https://unpaywall.org/sources). 

Is there anything I can do to help with this issue?

**Comment by hpiwowar** [comment]
Hi!  Thanks for reporting it!  We'll get it fixed.
Best,
Heather

--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by richard-orr** [comment]
Not sure what the issue was, but we found both of these on HAL Inserm.
