### ISSUE TITLE
Shortcut DOI links no longer working?

### ISSUE THREAD

**Issue by ioverka** [Impactstory/unpaywall#39]
Hi,

https://unpaywall.org/integrations states:

> the shortcut link https://unpaywall.org/YOUR_DOI automatically redirects to an open version of YOUR_DOI if we have one;

However this syntax doesn't seem to work any longer, e.g. https://api.unpaywall.org/v2/10.3733/ca.2016a0025?email=xxx@xxx returns `"is_oa": true,` and several oa_locations. But https://unpaywall.org/10.3733/ca.2016a0025 doesn't redirect to any of them.

Thanks & have a nice weekend,
inga

**Comment by hpiwowar** [comment]
Thanks for letting us know!  Will look into soon.

**Comment by richard-orr** [comment]
I can't replicate this anymore.

https://unpaywall.org/10.3733/ca.2016a0025 redirects to http://calag.ucanr.edu/archive/?type=pdf&article=ca.2016a0025, which is currently the best location's URL from https://api.unpaywall.org/v2/10.3733/ca.2016a0025?email=richard@unpaywall.org.
