### ISSUE TITLE
In Firefox, use toolbar icon instead of drawing it on the page

### ISSUE THREAD

**Issue by protist** [Impactstory/unpaywall#4]
I just installed the new Firefox add-on. It seems to be working pretty well!

However, I wondered if it could be made less intrusive. Since users have have the option of putting the icon in the toolbar anyway, could that change colour and provide access to papers, instead of having the icon drawn on the webpage itself?

I guess making this an option would be one strategy, but I think the toolbar icon should at least provide full functionality, otherwise it's not particularly useful anyway.

**Comment by waldyrious** [comment]
Another option would be the address bar. I know it was possible for older extensions, but I'm not sure recent versions of Firefox support this. If possible, that'd be even less intrusive than the toolbar :)

**Comment by jasonpriem** [comment]
Sorry for the delay in responding! Those are both reasonable suggestions. However, so far most of our users have expressed a preference for the tab directly on the page. In most cases this doesn't cover anything important, and it only appears on scholarly articles. So I think for the time being we'll be sticking to this approach, unless we begin to hear more feedback expressing concern. Thanks though for taking the time to let us know your ideas!

**Comment by caesar** [comment]
This is a pretty major issue for me. I really hate addons which mess with the page content unnecessarily (it makes it hard to tell whether the icon is browser chrome or webpage content - thereby making phishing attacks that much easier). The toolbar icon is the correct way to go.

Normally I would immediately uninstall an addon which did this. So far I am making an exception for Unpaywall, at least while I try it out, but I really hope you will reconsider this decision.

Thanks for the useful tool, anyway! 👍

**Comment by jasonpriem** [comment]
Thanks for the feedback, @caesar!

**Comment by katrinleinweber** [comment]
How about a 2nd option besides `Color-code tab for Green and Gold OA`: `Use toolbar icon instead of tab on the page`?

Or, an option to chose the placement, like it's possible for the Windows Taskbar and the macOS Dock: `left`, `top`, `right`, `bottom`?
