### ISSUE TITLE
False positive: link to biorxiv

### ISSUE THREAD

**Issue by cmaumet** [Impactstory/unpaywall#41]
Hi! Thanks for unpaywall, this is a great tool! 

On this manuscript page https://doi.org/10.1038/s41592-018-0235-4 the unpaywall buttton returns: "The Unpaywall extension couldn't find any legal open-access version of this article."

while the manuscript is openly available on biorxiv: https://doi.org/10.1101/306951.

**Comment by richard-orr** [comment]
This is a great example to have; it looks like we could use the [published article's metadata](https://api.crossref.org/v1/works/http://dx.doi.org/10.1038/s41592-018-0235-4) to associate it with the preprint.

In the meantime, we've added the link manually Thanks for pointing this out!
