### ISSUE TITLE
Unpaywall not working on distill.pub articles

### ISSUE THREAD

**Issue by ShadowMitia** [Impactstory/unpaywall#42]
On the https://distill.pub website, unpaywall is finding articles, but as far as I can see none of them are related to the article on the page.

For exemple on this page https://distill.pub/2017/aia/, unpaywall shows up with a green icon, but the linked article (https://arxiv.org/pdf/1609.04468.pdf) doesn't seem to be at all related to the distill page at first, but it is in fact in the references of that page, with a pdf to the article.

Also this page on distill https://distill.pub/2019/activation-atlas/ seems to be working properly (unpaywall just loops back to the same page, I don't know if it's the intended behavior).

**Comment by richard-orr** [comment]
Thanks for pointing this out. We fixed the links to the PDFs from the reference sections. Given that the full text is available on the distill.pub landing page, linking back there is expected.

All articles from this journal now link back to their landing pages.
