### ISSUE TITLE
Use multiple OA sources

### ISSUE THREAD

**Issue by nicebread** [Impactstory/unpaywall#5]
Thanks for the great plugin!
There is another OA doi resolver: http://doai.io/

In my experience, this sometimes finds OA PDFs where https://oadoi.org/ cannot find one. Would be great to have the unpaywall button as one aggregator that collects them all.

**Comment by jibe-b** [comment]
Note that doai.io gets pdf on ResearchGate.

**Comment by jasonpriem** [comment]
Agree, @nicebread, our goal with Unpaywall is indeed to collect every (legal) OA copy we can. Our tests so far have mostly found that DOAI does not increase coverage much. That said, if you have any examples where DOAI is finding OA and Unpaywall isn't, we'd love to see them...we can either add DOAI coverage or improve oaDOI (the API behind Unpaywall) so we're not missing them anymore.
