### ISSUE TITLE
Problems with multiple DOIs in one page

### ISSUE THREAD

**Issue by hauschke** [Impactstory/unpaywall#6]
Example: https://vivo.tib.eu/fis/individual?uri=http%3A%2F%2Fd-nb.info%2Fgnd%2F123841704

1. Browser: Vivaldi 1.8.770.50 (Stable channel) (32-Bit)

There are links to two DOIs in this page. Unpaywall recognizes only the first one.

2. Browser: Firefox 52.0.1 (32-Bit)

Same page, Unpaywall does not recognize any article.

**Comment by jasonpriem** [comment]
Thanks very much for filing this issue. Especially in these early days, bug reports from users are very important to us, and we really appreciate your taking the time.

It looks like the Firefox extension is behaving correctly here, and the Chrome/Vivaldi one is not. We are only supposed to work on article landing pages--that is, pages that have a one-to-one relationship with a given scholarly article. 

I will update the Chrome extension to fix this.

**Comment by jasonpriem** [comment]
I've pushed the update to the Chrome Web Store. Generally takes a 4-24hrs before Chrome's update system gets new versions pushed out to users. If it's not fixed on your machine tomorrow, let us know.
