### ISSUE TITLE
Publisher landing page not recognized

### ISSUE THREAD

**Issue by ioverka** [Impactstory/unpaywall#7]
Browser: Chrome 56.0.2924.87 (64-bit), Unpaywall 1.6.1

I checked a couple of publisher platforms today, here is a short list of landing pages where the amazing Unpaywall button has not appeared:
* AMS, http://www.ams.org/journals/era/2004-10-13/S1079-6762-04-00136-2/home.html
* APA PsycNet: http://psycnet.apa.org/?&fa=main.doiLanding&doi=10.1037/h0027297 
* IEEE XPlore: http://ieeexplore.ieee.org/document/4302745/

... but overall the coverage is pretty impressive for a prerelease! One question out of curiosity: How does the Unpaywall plugin detects article landing pages?

**Comment by jasonpriem** [comment]
will push this to the chrome web store later today...

**Comment by jasonpriem** [comment]
Pushed to production! Your three examples now work correctly. The changes are in version 1.6.2, now in the Chrome Web Store. Your Chrome will auto-update to use that version...generally happens within a few hours.  Thanks again so much for letting us know, and including examples. Very helpful.
